version: 2.1
executors:
  npm-executor:
    docker:
      - image: circleci/node:10
    working_directory: ~/workspace
jobs:
  install:
    executor: npm-executor
    resource_class: small
    steps:
      - checkout
      - restore_cache:
          keys:
            - key-{{ checksum "package.json" }}
      - run:
          name: install
          command: |
            npm ci
      - save_cache:
          key: key-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/workspace/node_modules
      - persist_to_workspace:
          root: ~/
          paths:
            - workspace
            - .npm
  test:
    executor: npm-executor
    resource_class: small
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: run test
          command: |
            npm run test
  build:
    executor: npm-executor
    resource_class: small
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Build
          command: |
            npm run build
  publish:
    executor: npm-executor
    resource_class: small
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: publish release package to npm registry
          command: |
            echo "//registry.npmjs.org/:_authToken=${NPM_PUBLISH_TOKEN}" > .npmrc
            npm publish --access public

workflows:
  version: 2.1
  ci-checks:
    jobs:
      - install:
          filters:
            tags:
              only: /^v.*/
      - test:
          requires:
            - install
          filters:
            tags:
              only: /^v.*/
      - build:
          requires:
            - install
          filters:
            tags:
              only: /^v.*/
      - publish:
          context: Build
          requires:
            - test
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/