version: 2.1
executors:
  npm-executor:
    docker:
      - image: circleci/node:10
    working_directory: ~/workspace
jobs:
  install:
    executor: npm-executor
    resource_class: small
    steps:
      - checkout
      - restore_cache:
          keys:
            - key-{{ checksum "package.json" }}
      - run:
          name: install
          command: |
            npm ci
      - save_cache:
          key: key-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/workspace/node_modules
      - persist_to_workspace:
          root: ~/
          paths:
            - workspace
            - .npm
  test:
    executor: npm-executor
    resource_class: small
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: run test
          command: |
            npm run test
  build:
    executor: npm-executor
    resource_class: small
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Build
          command: |
            npm run build
      - persist_to_workspace:
          root: ~/
          paths:
            - workspace
            - .npm
  publish:
    description: "Publish package aritfacts to a specified registry"
    executor: npm-executor
    resource_class: small
    parameters:
      registry:
        default: registry.npmjs.org
        type: string
      token_var:
        default: NPM_PUBLISH_TOKEN
        type: string
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: publish release package to npm registry
          command: |
            echo "@twyla-ai:registry=https://<< parameters.registry >>/" > .npmrc
            echo "//<< parameters.registry >>/:_authToken=${<< parameters.token_var >>}" >> .npmrc
            npm publish --access public

workflows:
  ci-checks:
    jobs:
      - install:
          filters:
            tags:
              only: /^v?([0-9].*\.[0-9].*\.[0-9].*)$/
      - test:
          requires:
            - install
          filters:
            tags:
              only: /^v?([0-9].*\.[0-9].*\.[0-9].*)$/
      - build:
          requires:
            - install
          filters:
            tags:
              only: /^v?([0-9].*\.[0-9].*\.[0-9].*)$/
      - publish:
          name: Publish to npmjs.org
          registry: registry.npmjs.org
          token_var: NPM_PUBLISH_TOKEN
          context: Build
          requires:
            - test
            - build
          filters:
            tags:
              only: /^v?([0-9].*\.[0-9].*\.[0-9].*)$/
            branches:
              ignore: /.*/
      - publish:
          name: Publish to GitHub Package Registry
          registry: npm.pkg.github.com
          token_var: GITHUB_REGISTRY_ACCESS_TOKEN
          context: Build
          requires:
            - test
            - build
          filters:
            tags:
              only: /^v?([0-9].*\.[0-9].*\.[0-9].*)$/
            branches:
              ignore: /.*/
