name: Release Workflow

on:
  release:
    types: [published]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    name: Publish package (registry.npmjs.org)
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
          registry-url: https://registry.npmjs.org/
      - name: Publish Package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public

  publish-gh:
    runs-on: ubuntu-latest
    name: Publish package (npm.pkg.github.com)
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
          registry-url: https://npm.pkg.github.com/twyla-ai
      - name: Publish Package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm publish --access public
