name: Release Workflow

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish package to registries
    steps:
      - uses: actions/checkout@v2
      - name: Setup node (registry.npmjs.org)
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: https://registry.npmjs.org/
      - name: Install package dependencies
        run: npm ci
      - name: Build package
        run: npm run build
      - name: Publish Package (registry.npmjs.org)
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public
      - name: Setup node (npm.pkg.github.com)
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: https://npm.pkg.github.com/twyla-ai
      - name: Publish Package (npm.pkg.github.com)
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm publish --access public
